name: led_control
publish_to: 'none'
description: Aplicativo Flutter para controlar um LED no ESP32 via Wi-Fi.
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
flutter:
  uses-material-design: true
